#!/usr/bin/env bash
set -euo pipefail

SNIPPET_DIR="${SNIPPET_DIR:-/etc/nginx/snippets}"
ALLOW_SNIPPET="${ALLOW_SNIPPET:-${SNIPPET_DIR}/cloudflare-origin-allow.conf}"
NGINX_BIN="${NGINX_BIN:-nginx}"
SYSTEMCTL_BIN="${SYSTEMCTL_BIN:-systemctl}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

IPV4_URL="https://www.cloudflare.com/ips-v4"
IPV6_URL="https://www.cloudflare.com/ips-v6"
IPV4_FILE="${TMP_DIR}/ips-v4"
IPV6_FILE="${TMP_DIR}/ips-v6"
GENERATED_SNIPPET="${TMP_DIR}/cloudflare-origin-allow.conf"

mkdir -p "${SNIPPET_DIR}"

curl -fsSL "${IPV4_URL}" -o "${IPV4_FILE}"
curl -fsSL "${IPV6_URL}" -o "${IPV6_FILE}"

validate_ipv4_cidrs() {
  local file="$1"
  local line
  local address
  local prefix
  local count=0
  local octet
  local -a octets

  while IFS= read -r line || [ -n "${line}" ]; do
    [ -z "${line}" ] && continue
    count=$((count + 1))
    if [[ ! "${line}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$ ]]; then
      echo "Unexpected IPv4 CIDR from Cloudflare: ${line}" >&2
      return 1
    fi
    address="${line%/*}"
    prefix="${line#*/}"
    IFS=. read -r -a octets <<< "${address}"
    for octet in "${octets[@]}"; do
      if ((10#${octet} > 255)); then
        echo "Unexpected IPv4 CIDR from Cloudflare: ${line}" >&2
        return 1
      fi
    done
    if ((prefix > 32)); then
      echo "Unexpected IPv4 CIDR from Cloudflare: ${line}" >&2
      return 1
    fi
  done < "${file}"

  if ((count == 0)); then
    echo "Cloudflare IPv4 range list was empty" >&2
    return 1
  fi
}

validate_ipv6_cidrs() {
  local file="$1"
  local line
  local count=0

  while IFS= read -r line || [ -n "${line}" ]; do
    [ -z "${line}" ] && continue
    count=$((count + 1))
    if [[ ! "${line}" =~ ^[0-9A-Fa-f:]+/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8])$ ]]; then
      echo "Unexpected IPv6 CIDR from Cloudflare: ${line}" >&2
      return 1
    fi
  done < "${file}"

  if ((count == 0)); then
    echo "Cloudflare IPv6 range list was empty" >&2
    return 1
  fi
}

write_allow_rules() {
  local file="$1"
  local cidr

  while IFS= read -r cidr || [ -n "${cidr}" ]; do
    [ -z "${cidr}" ] && continue
    printf 'allow %s;\n' "${cidr}"
  done < "${file}"
}

validate_ipv4_cidrs "${IPV4_FILE}"
validate_ipv6_cidrs "${IPV6_FILE}"

{
  echo "# Generated by update-cloudflare-origin-allowlist.sh"
  echo "# Allows direct web traffic only from Cloudflare edge ranges."
  echo "# Source: ${IPV4_URL}"
  echo "# Source: ${IPV6_URL}"
  echo "allow 127.0.0.1;"
  echo "allow ::1;"
  write_allow_rules "${IPV4_FILE}"
  write_allow_rules "${IPV6_FILE}"
  echo "deny all;"
} > "${GENERATED_SNIPPET}"

install -m 0644 "${GENERATED_SNIPPET}" "${ALLOW_SNIPPET}"

"${NGINX_BIN}" -t
"${SYSTEMCTL_BIN}" reload nginx
