#!/usr/bin/env bash
set -euo pipefail

SNIPPET_DIR="${SNIPPET_DIR:-/etc/nginx/snippets}"
ALLOW_SNIPPET="${ALLOW_SNIPPET:-${SNIPPET_DIR}/cloudflare-origin-allow.conf}"
NGINX_BIN="${NGINX_BIN:-nginx}"
SYSTEMCTL_BIN="${SYSTEMCTL_BIN:-systemctl}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

IPV4_URL="https://www.cloudflare.com/ips-v4"
IPV6_URL="https://www.cloudflare.com/ips-v6"
IPV4_FILE="${TMP_DIR}/ips-v4"
IPV6_FILE="${TMP_DIR}/ips-v6"
NORMALIZED_IPV4_FILE="${TMP_DIR}/ips-v4.normalized"
NORMALIZED_IPV6_FILE="${TMP_DIR}/ips-v6.normalized"
GENERATED_SNIPPET="${TMP_DIR}/cloudflare-origin-allow.conf"
CANDIDATE_NGINX_CONFIG="${TMP_DIR}/nginx-candidate.conf"
SNIPPET_BASENAME="$(basename "${ALLOW_SNIPPET}")"
INSTALL_TMP=""
BACKUP_SNIPPET=""

mkdir -p "${SNIPPET_DIR}"

curl -fsSL --retry 3 --retry-delay 5 --connect-timeout 10 --max-time 60 "${IPV4_URL}" -o "${IPV4_FILE}"
curl -fsSL --retry 3 --retry-delay 5 --connect-timeout 10 --max-time 60 "${IPV6_URL}" -o "${IPV6_FILE}"

normalize_and_validate_cidrs() {
  local family="$1"
  local input_file="$2"
  local output_file="$3"

  python3 -c '
import ipaddress
import sys

family = sys.argv[1]
input_path = sys.argv[2]
output_path = sys.argv[3]
version = 4 if family == "IPv4" else 6
count = 0

with open(input_path, "r", encoding="utf-8", newline="") as source, open(output_path, "w", encoding="utf-8") as dest:
    for number, raw_line in enumerate(source, 1):
        line = raw_line.rstrip("\n").rstrip("\r")
        if not line or line.startswith("#"):
            continue
        if line != line.strip() or any(char.isspace() for char in line) or "#" in line or ";" in line:
            print(f"Unexpected {family} CIDR from Cloudflare on line {number}: {line!r}", file=sys.stderr)
            sys.exit(1)
        try:
            network = ipaddress.ip_network(line, strict=False)
        except ValueError:
            print(f"Unexpected {family} CIDR from Cloudflare on line {number}: {line!r}", file=sys.stderr)
            sys.exit(1)
        if network.version != version:
            print(f"Unexpected {family} CIDR from Cloudflare on line {number}: {line!r}", file=sys.stderr)
            sys.exit(1)
        dest.write(f"{network.with_prefixlen}\n")
        count += 1

if count == 0:
    print(f"Cloudflare {family} range list was empty", file=sys.stderr)
    sys.exit(1)
' "${family}" "${input_file}" "${output_file}"
}

write_allow_rules() {
  local file="$1"
  local cidr

  while IFS= read -r cidr || [ -n "${cidr}" ]; do
    [ -z "${cidr}" ] && continue
    printf 'allow %s;\n' "${cidr}"
  done < "${file}"
}

normalize_and_validate_cidrs "IPv4" "${IPV4_FILE}" "${NORMALIZED_IPV4_FILE}"
normalize_and_validate_cidrs "IPv6" "${IPV6_FILE}" "${NORMALIZED_IPV6_FILE}"

{
  echo "# Generated by update-cloudflare-origin-allowlist.sh"
  echo "# Allows direct web traffic only from Cloudflare edge ranges."
  echo "# Source: ${IPV4_URL}"
  echo "# Source: ${IPV6_URL}"
  echo "allow 127.0.0.1;"
  echo "allow ::1;"
  write_allow_rules "${NORMALIZED_IPV4_FILE}"
  write_allow_rules "${NORMALIZED_IPV6_FILE}"
  echo "deny all;"
} > "${GENERATED_SNIPPET}"

cat > "${CANDIDATE_NGINX_CONFIG}" <<EOF
events {}
http {
    server {
        listen 127.0.0.1:8080;
        location / {
            include ${GENERATED_SNIPPET};
        }
    }
}
EOF

"${NGINX_BIN}" -t -c "${CANDIDATE_NGINX_CONFIG}" -g "pid ${TMP_DIR}/nginx.pid;"

INSTALL_TMP="$(mktemp "${SNIPPET_DIR}/.${SNIPPET_BASENAME}.tmp.XXXXXX")"
install -m 0644 "${GENERATED_SNIPPET}" "${INSTALL_TMP}"

if [ -e "${ALLOW_SNIPPET}" ]; then
  BACKUP_SNIPPET="${TMP_DIR}/${SNIPPET_BASENAME}.backup"
  cp -p "${ALLOW_SNIPPET}" "${BACKUP_SNIPPET}"
fi

mv "${INSTALL_TMP}" "${ALLOW_SNIPPET}"

if ! "${NGINX_BIN}" -t; then
  if [ -n "${BACKUP_SNIPPET}" ] && [ -e "${BACKUP_SNIPPET}" ]; then
    install -m 0644 "${BACKUP_SNIPPET}" "${ALLOW_SNIPPET}"
    "${NGINX_BIN}" -t || true
  fi
  exit 1
fi
"${SYSTEMCTL_BIN}" reload nginx
